### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by moh3th1** [nilboy/tensorflow-yolo#1]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.I want to fine tune your model on my data which has only two classes ?

**Comment by nilboy** [comment]
you can reference to readme.md.

1. download my pretrain model
2. write your own configure file, referencing to
https://github.com/nilboy/tensorflow-yolo/blob/master/conf/train.cfg .
change num_classes to 2
3. transform your training data to text_record file(the format reference to
pascal_voc)
4. train (python tools/train.py -c $your_configure_file)

2016-10-31 22:59 GMT+08:00 moh3th1 <notifications@github.com>:

**Comment by moh3th1** [comment]
@nilboy 
I tried your instructions but I got this error 
![screenshot from 2016-11-08 18-35-18](https://cloud.githubusercontent.com/assets/15180702/20107702/235cfbbe-a5e2-11e6-84b5-66ba860a5a64.png)

**Comment by nilboy** [comment]
you should confirm that the image path is correct.

2016-11-09 0:35 GMT+08:00 moh3th1 <notifications@github.com>:
