### ISSUE TITLE
Training Run-time Error

### ISSUE THREAD

**Issue by aliceyayunji** [nilboy/tensorflow-yolo#11]
I downloaded the code and the tiny yolo pretrain model, change nothing but Error Occurs.
Environment : 
TensorFlow 1.0
GPU Titan X 
Python 2.7 

![image](https://cloud.githubusercontent.com/assets/8035537/24288795/ad32b2a6-10b9-11e7-8080-ca4ddf22aae4.png)
 
When change the config to use YoloNet there's no such problem, but the pretrain model doesn't fit ...

**Comment by nilboy** [comment]
Please make sure you use the correct tensorflow version(1.0), because the tf.concat api has changed from tf-1.0. you can reference to http://stackoverflow.com/questions/41813665/tensorflow-slim-typeerror-expected-int32-got-list-containing-tensors-of-type

**Comment by aliceyayunji** [comment]
It is the problem about the tensorflow version. Reference to the link nilboy supply, I solved the problem: just change the code in yolo_tiny_net.py : 
#predicts = tf.concat([class_probs, scales, boxes], 3)
to 
 predicts = tf.concat(3,[class_probs, scales, boxes])
and it can run ok.
