### ISSUE TITLE
An error occurred in "./yolo/net/net.py" in Branch "python 3"

### ISSUE THREAD

**Issue by Liang-yc** [nilboy/tensorflow-yolo#12]
Hi, I tried to run this code with Branch "python 3". Howerver, as I have used the tensorflow ver1.0, the error "module 'tensorflow' has no attribute 'mul'" occurred in this file("./yolo/net/net.py"); 
![qq 20170329144136](https://cloud.githubusercontent.com/assets/25114561/24441813/f29452d2-148d-11e7-95a0-62bd3076f78a.jpg)
then I replaced "tf.mul" with "tf.matmul", another error "ValueError: Shape must be rank 2 but is rank 0 for 'conv1/weight_loss' Mul'.... " occurred.  As I am not good at python programming, I cannot put it right.
    Noticing that you are still maintaining this project in Branch "python 2.7", so, can you help me solve this problem?(I ran this project with W7 x64, the python version is 3.5.2)

**Comment by nilboy** [comment]
you should use 'tf.multiply' to replace 'tf.mul'

**Comment by Liang-yc** [comment]
Thanks for your reply. I have replaced it and other functions which have been discarded in Tensorflow 1.0(the files which need to be modified are in `./yolo/net` folder). All in all, it seems that it can work now . Thank you.
