### ISSUE TITLE
Cant not use pretrained model

### ISSUE THREAD

**Issue by phongnhhn92** [nilboy/tensorflow-yolo#14]
I used this python3 branch to re implement your code. However, i have this error :'( Please help me 
![1](https://cloud.githubusercontent.com/assets/11288381/24599211/0ed82068-188a-11e7-9e10-4fb5effb81a7.png)
![2](https://cloud.githubusercontent.com/assets/11288381/24599215/10c50cba-188a-11e7-9304-9bb79bdebffa.png)

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader construc
tor: Failed to find any matching files for F:\\yolo_tiny.ckpt
[[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:l
ocalhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_5/tensor_na
mes, save/RestoreV2_5/shape_and_slices)]]

**Comment by nilboy** [comment]
don't find F:\yolo_tiny.ckpt ; please make sure that you have file F:\yolo_tiny.ckpt.
