### ISSUE TITLE
can not run train.py

### ISSUE THREAD

**Issue by xray1111** [nilboy/tensorflow-yolo#18]
When I type in "python tools/train.py -c conf/train.cfg", it report the error:

Traceback (most recent call last):
  File "tools/train.py", line 6, in <module>
    import yolo
  File "./yolo/__init__.py", line 1, in <module>
    import dataset
ModuleNotFoundError: No module named 'dataset'

I'm using anaconda3 BTW. 
Thank you for your help!

**Comment by xray1111** [comment]
OK, I found the cause: should use the version for python3

**Comment by shiwenhao** [comment]
when I run 'demo.py', I meet the same problems with you , I am using anaconda3 and the version for python3,Do you have the problem?
Thank you for your help!

**Comment by ndaidong** [comment]
It looks like this demo only works with Python 2.x?
