### ISSUE TITLE
Why only an object can be identified, other objects can't be identified?

### ISSUE THREAD

**Issue by leeyoshinari** [nilboy/tensorflow-yolo#25]
When I run the demo.py, I get the follow image.
![2007_006317_out1](https://user-images.githubusercontent.com/25929786/28006627-bc0a0f86-6582-11e7-964e-6389a01ab54d.jpg)
I train the model 20,000 steps. Only a person is identified, the bus and bicycly can't be identified. Other images with many objects are the same. How can I modify the code to identify the all objects? Thank you!

**Comment by nilboy** [comment]
You can identify whether the box is an object according to the value of C.  https://github.com/nilboy/tensorflow-yolo/blob/python2.7/demo.py#L19

**Comment by leeyoshinari** [comment]
[https://github.com/nilboy/tensorflow-yolo/blob/python2.7/demo.py#L25](url)
index = np.argmax(P)
It seems to only find the maximum value, only one object.

**Comment by ss199302** [comment]
你好，请问你解决这个问题了吗，具体是怎么做的啊，谢谢

**Comment by wenbowen123** [comment]
@leeyoshinari  Did you train from scratch or did you train starting from the initial weight file?
