### ISSUE TITLE
no module name net during running...

### ISSUE THREAD

**Issue by Jakesh-Bohaju** [nilboy/tensorflow-yolo#37]
Traceback (most recent call last):
  File "E:\python_workspace\tensorflow-yolo\demo.py", line 5, in <module>
    from yolo.net.yolo_tiny_net import YoloTinyNet 
  File "E:\python_workspace\tensorflow-yolo\yolo\__init__.py", line 2, in <module>
    import net
ModuleNotFoundError: No module named 'net'

**Comment by YefeiGao** [comment]
maybe u can just comment all that import process within __init__.py files, this works for me with gpu mode @Jakesh-Bohaju

**Comment by YefeiGao** [comment]
maybe u can just comment all that import process within __init\__.py files, like:
```
e.g. for __init__.py in $tensorflow-yolo-python3/yolo/
# import dataset
# import net
# import solver
```
this works for me with gpu mode @Jakesh-Bohaju

**Comment by Jakesh-Bohaju** [comment]
how to run with gpu mode?
thanks in advance

**Comment by YefeiGao** [comment]
Just install tensorflow-gpu if u want run with gpu mode. In fact I have also run this demo with cpu mode. I folked this repository and added multi-object detection, hope that can help u! @Jakesh-Bohaju 
[https://github.com/YefeiGao/YOLO-Tensorflow](https://github.com/YefeiGao/YOLO-Tensorflow)

**Comment by Jakesh-Bohaju** [comment]
Thanks for your help

During running preprocess_pascal_voc.py following error occur


PS E:\python_workspace\YOLO-Tensorflow\tools> python preprocess_pascal_voc.py
Traceback (most recent call last):
  File "preprocess_pascal_voc.py", line 82, in <module>
    main()
  File "preprocess_pascal_voc.py", line 64, in main
    out_file = open(OUTPUT_PATH, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\python_workspace\\YOLO-Tensorflow\\tools\\data/pascal_voc.txt'

How to solve this problem? @YefeiGao

**Comment by YefeiGao** [comment]
Hi @Jakesh-Bohaju , hope u have got the answer. You may check if the pascal_voc.txt file can be loaded successfully and 'w' means open that file with write access.

**Comment by Jakesh-Bohaju** [comment]
{Extract all of these tars into one directory named VOCdevkit

tar xvf VOCtrainval_06-Nov-2007.tar
tar xvf VOCtest_06-Nov-2007.tar
It should have this basic structure

$VOCdevkit/                           # development kit
$VOCdevkit/VOCcode/                   # VOC utility code
$VOCdevkit/VOC2007                    # image sets, annotations, etc.
# ... and several other directories ...
}

On extraction all these files does not found 
Both of them contain same file like
annotations, imageset, jpegimages, segmentationclass, segmentationobject only
Would you please send the correct link to download and if latest version data acceptable them prefer latest one. Thanks again

@YefeiGao

**Comment by ss199302** [comment]
@YefeiGao If I just want to train a class, how do I modify the code？thanks
